spring:
  application:
    name: aggregateservice

services:
  uri:
    helloservice: http://helloservice:8081/hello
    worldservice: http://worldservice:8082/world

opentracing:
  jaeger:
    udp-sender:
      host: jaeger-collector.istio-system
      port: 14268
