spring:
  application:
    name: aggregateservice

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system:14268/api/traces

services:
  uri:
    helloservice: http://helloservice:8081/hello
    worldservice: http://worldservice:8082/world
