---
# Source: aggregateservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aggregateservice
  labels:
    helm.sh/chart: aggregateservice-0.1.0
    app: aggregateservice
    version: v1
    app.kubernetes.io/name: aggregateservice
    app.kubernetes.io/instance: aggregateservice
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
---
# Source: aggregateservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aggregateservice
  labels:
    helm.sh/chart: aggregateservice-0.1.0
    app: aggregateservice
    version: v1
    app.kubernetes.io/name: aggregateservice
    app.kubernetes.io/instance: aggregateservice
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8080
      protocol: TCP
      name: nginx
  selector:
    app: aggregateservice
    version: v1
    app.kubernetes.io/name: aggregateservice
    app.kubernetes.io/instance: aggregateservice
---
# Source: aggregateservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregateservice
  labels:
    helm.sh/chart: aggregateservice-0.1.0
    app: aggregateservice
    version: v1
    app.kubernetes.io/name: aggregateservice
    app.kubernetes.io/instance: aggregateservice
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregateservice
      version: v1
      app.kubernetes.io/name: aggregateservice
      app.kubernetes.io/instance: aggregateservice
  template:
    metadata:
      labels:
        app: aggregateservice
        version: v1
        app.kubernetes.io/name: aggregateservice
        app.kubernetes.io/instance: aggregateservice
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: aggregateservice
      securityContext:
        {}
      containers:
        - name: aggregateservice
          securityContext:
            {}
          image: "docker.pkg.github.com/300kks/aggregateservice/aggregateservice:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
          resources:
            {}

